// Generated by CoffeeScript 1.6.3
(function() {
  var q;

  q = function(query) {
    return document.querySelector(query);
  };

  define(function(require, exports) {
    var cirru, compact, mustache, req, show;
    cirru = require("cirru");
    compact = require("compact");
    cirru.parse.compact = true;
    mustache = require("./mustache");
    req = new XMLHttpRequest;
    req.open("get", "./cirru/div.cr");
    req.send();
    req.onload = function() {
      var content;
      content = req.responseText;
      return show(content);
    };
    show = function(text) {
      var html, tree;
      q(".source").value = text;
      tree = cirru.parse(text);
      html = mustache.render(tree);
      q(".target").value = html;
      console.clear();
      return console.log(compact.render(tree));
    };
    return q(".source").onkeyup = function() {
      return show(this.value);
    };
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
